import json

from automation.models import (
    CapabilityArtifact,
)


ARTIFACT_PATH = (
    "artifacts/discovered_get_savings_balance.json"
)


def load_artifact():
    with open(
        ARTIFACT_PATH,
        "r",
        encoding="utf-8",
    ) as file:
        return json.load(file)


def test_discovered_artifact_is_valid():
    """
    The artifact generated by discovery must
    conform to our capability schema.
    """

    data = load_artifact()

    artifact = (
        CapabilityArtifact.model_validate(
            data
        )
    )

    assert artifact.capability_id == (
        "get_savings_balance"
    )


def test_artifact_has_member_input():
    data = load_artifact()

    member_input = next(
        item
        for item in data["inputs"]
        if item["name"] == "member_id"
    )

    assert member_input["type"] == "string"
    assert member_input["required"] is True


def test_artifact_has_savings_output():
    data = load_artifact()

    savings_output = next(
        item
        for item in data["outputs"]
        if item["name"] == "savings_balance"
    )

    assert savings_output["type"] == "string"


def test_artifact_parameterizes_member_id():
    """
    Discovery used member 12345, but the
    compiled artifact must not be tied to it.
    """

    data = load_artifact()

    values = [
        step.get("value")
        for step in data["steps"]
    ]

    assert "{{member_id}}" in values


def test_artifact_has_success_condition():
    data = load_artifact()

    success = data["success_condition"]

    assert success["type"] == "output_present"
    assert success["expected"] == (
        "savings_balance"
    )