import json

from playwright.sync_api import sync_playwright

from automation.discovery_executor import (
    execute_discovery_action,
)
from automation.discovery_llm import (
    choose_next_action,
)
from automation.discovery_models import (
    DiscoveryActionType,
)
from automation.surface import WebSurface
from automation.compiler import (
    compile_discovery_to_artifact,
)


START_URL = "http://127.0.0.1:8000"
MAX_STEPS = 10


def run_discovery(
    goal: str,
) -> dict:

    history = []
    extracted_data = {}

    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=False
        )

        page = browser.new_page()
        surface = WebSurface(page)

        surface.open(START_URL)

        try:
            for step_number in range(
                1,
                MAX_STEPS + 1,
            ):
                print()
                print(
                    f"===== DISCOVERY STEP "
                    f"{step_number} ====="
                )

                # -------------------------
                # Observe current UI
                # -------------------------

                observation = (
                    surface.observe()
                )

                print(
                    "Current page:",
                    observation["title"],
                )

                # -------------------------
                # Build discovery context
                # -------------------------

                context = {
                    **observation,
                    "history": history,
                    "extracted_data": (
                        extracted_data
                    ),
                }

                # -------------------------
                # Ask LLM what to do
                # -------------------------

                action = (
                    choose_next_action(
                        goal,
                        context,
                    )
                )

                print("LLM ACTION:")
                print(
                    action.model_dump_json(
                        indent=2
                    )
                )

                # -------------------------
                # Human escalation
                # -------------------------

                if (
                    action.action
                    == DiscoveryActionType.ESCALATE
                ):
                    result = {
                        "status": "escalated",
                        "reason": action.reason,
                        "history": history,
                        "extracted_data": (
                            extracted_data
                        ),
                    }

                    print()
                    print(
                        "DISCOVERY ESCALATED"
                    )

                    return result

                # -------------------------
                # Finish
                # -------------------------

                if (
                    action.action
                    == DiscoveryActionType.FINISH
                ):
                    # Start with whatever the
                    # LLM returned.
                    final_output_name = (
                        action.output_name
                    )

                    final_output_value = (
                        action.output_value
                    )

                    # Prefer data actually extracted
                    # from the browser over a value
                    # repeated/generated by the LLM.
                    if extracted_data:
                        final_output_name = next(
                            iter(extracted_data)
                        )

                        extracted_result = (
                            extracted_data[
                                final_output_name
                            ]
                        )

                        final_output_value = (
                            extracted_result.get(
                                "output_value"
                            )
                        )

                    result = {
                        "status": "success",
                        "output_name": (
                            final_output_name
                        ),
                        "output_value": (
                            final_output_value
                        ),
                        "history": history,
                        "extracted_data": (
                            extracted_data
                        ),
                    }

                    print()
                    print(
                        "DISCOVERY COMPLETE"
                    )

                    return result

                # -------------------------
                # Execute action
                # -------------------------

                execution_result = (
                    execute_discovery_action(
                        surface,
                        action,
                    )
                )

                # -------------------------
                # Handle extraction
                # -------------------------

                if (
                    action.action
                    == DiscoveryActionType.EXTRACT
                    and execution_result
                    is not None
                ):
                    output_name = (
                        execution_result[
                            "output_name"
                        ]
                    )

                    extracted_data[
                        output_name
                    ] = execution_result

                    print(
                        "EXTRACTED:",
                        json.dumps(
                            execution_result,
                            indent=2,
                        ),
                    )

                # -------------------------
                # Record history
                # -------------------------

                history.append(
                    {
                        "step": step_number,
                        "action": (
                            action.action.value
                        ),
                        "target": (
                            action.target
                        ),
                        "value": (
                            action.value
                        ),
                        "reason": (
                            action.reason
                        ),
                        "execution_result": (
                            execution_result
                        ),
                    }
                )

            # -------------------------
            # Max-step protection
            # -------------------------

            return {
                "status": (
                    "max_steps_exceeded"
                ),
                "history": history,
                "extracted_data": (
                    extracted_data
                ),
            }

        finally:
            browser.close()


if __name__ == "__main__":
    goal = (
        "Find member 12345 and return "
        "their savings balance."
    )

    result = run_discovery(
        goal
    )

    print()
    print(
        "FINAL DISCOVERY RESULT:"
    )

    print(
        json.dumps(
            result,
            indent=2,
        )
    )

    # ---------------------------------------
    # Compile successful discovery
    # ---------------------------------------

    if result["status"] == "success":
        artifact = (
            compile_discovery_to_artifact(
                discovery_result=result,
                member_id="12345",
                output_path=(
                    "artifacts/"
                    "discovered_get_savings_balance.json"
                ),
            )
        )

        print()
        print(
            "COMPILED ARTIFACT:"
        )

        print(
            json.dumps(
                artifact,
                indent=2,
            )
        )